/*
## Rules for string to annagram of each other

1. Strings should not contain letter's other than alphabets i.e. (!, @, 1, 2 etc...)
2. String must be of same length.
3. Another string can be generated by rearraging the letter's of another string.

*/

//function for checking if letters other than alphabets exits in string;

const checkAlphbets = (String) => {
  //Regular expression
  const regExp = /[^a-zA-Z]/;
  const result = regExp.test(String);
  return result;
};

//Boolean function for checking annagram strings

const checkAnnagram = (string1, string2) => {
  //return false if chars other than alphbets exists
  if (checkAlphbets(string1) || checkAlphbets(string2)) return false;
  else {
    //sorting
    string1 = string1.split("").sort();
    string2 = string2.split("").sort();

    //converting array to string
    string1 = JSON.stringify(string1);
    string2 = JSON.stringify(string2);

    return string1 === string2;
  }
};
